var OAO=OAO||{};OAO.q=OAO.q||{};OAO.q.c=OAO.q.c||[];
(function(){var k=window.location.hostname||"",m,w,x;m=k.indexOf(".ionos.");w=k.indexOf(".server.lan");x=k.indexOf(".localhost");if(-1===m&&-1===w&&-1===x)return!1;m=k.substr(m+7);if(0===m.indexOf("de"))OAO.q.c.push(["setDefaultMarket","DE"]),OAO.q.c.push(["setDefaultLanguage","de_DE"]),OAO.q.c.push(["setDefaultTenant","IONOS_DE"]);else if(0===m.indexOf("ca"))OAO.q.c.push(["setDefaultMarket","CA"]),OAO.q.c.push(["setDefaultLanguage","en_CA"]),OAO.q.c.push(["setDefaultTenant","IONOS_CA"]);else if(0===
m.indexOf("es"))OAO.q.c.push(["setDefaultMarket","ES"]),OAO.q.c.push(["setDefaultLanguage","es_ES"]),OAO.q.c.push(["setDefaultTenant","IONOS_ES"]);else if(0===m.indexOf("fr"))OAO.q.c.push(["setDefaultMarket","FR"]),OAO.q.c.push(["setDefaultLanguage","fr_FR"]),OAO.q.c.push(["setDefaultTenant","IONOS_FR"]);else if(0===m.indexOf("it"))OAO.q.c.push(["setDefaultMarket","IT"]),OAO.q.c.push(["setDefaultLanguage","it_IT"]),OAO.q.c.push(["setDefaultTenant","IONOS_IT"]);else if(0===m.indexOf("mx"))OAO.q.c.push(["setDefaultMarket",
"MX"]),OAO.q.c.push(["setDefaultLanguage","es_MX"]),OAO.q.c.push(["setDefaultTenant","IONOS_MX"]);else if(0===m.indexOf("pl"))OAO.q.c.push(["setDefaultMarket","PL"]),OAO.q.c.push(["setDefaultLanguage","pl_PL"]),OAO.q.c.push(["setDefaultTenant","IONOS_PL"]);else if(0===m.indexOf("co.uk")||0===m.indexOf("uk"))OAO.q.c.push(["setDefaultMarket","UK"]),OAO.q.c.push(["setDefaultLanguage","en_GB"]),OAO.q.c.push(["setDefaultTenant","IONOS_UK"]);else if(0===m.indexOf("com"))OAO.q.c.push(["setDefaultMarket",
"US"]),OAO.q.c.push(["setDefaultLanguage","en_US"]),OAO.q.c.push(["setDefaultTenant","IONOS_US"]);else if(-1!==k.indexOf("de.")||-1!==k.indexOf("de-"))OAO.q.c.push(["setDefaultMarket","DE"]),OAO.q.c.push(["setDefaultLanguage","de_DE"]),OAO.q.c.push(["setDefaultTenant","IONOS_DE"]);else if(-1!==k.indexOf("ca.")||-1!==k.indexOf("ca-"))OAO.q.c.push(["setDefaultMarket","CA"]),OAO.q.c.push(["setDefaultLanguage","en_CA"]),OAO.q.c.push(["setDefaultTenant","IONOS_CA"]);else if(-1!==k.indexOf("es.")||-1!==
k.indexOf("es-"))OAO.q.c.push(["setDefaultMarket","ES"]),OAO.q.c.push(["setDefaultLanguage","es_ES"]),OAO.q.c.push(["setDefaultTenant","IONOS_ES"]);else if(-1!==k.indexOf("fr.")||-1!==k.indexOf("fr-"))OAO.q.c.push(["setDefaultMarket","FR"]),OAO.q.c.push(["setDefaultLanguage","fr_FR"]),OAO.q.c.push(["setDefaultTenant","IONOS_FR"]);else if(-1!==k.indexOf("it.")||-1!==k.indexOf("it-"))OAO.q.c.push(["setDefaultMarket","IT"]),OAO.q.c.push(["setDefaultLanguage","it_IT"]),OAO.q.c.push(["setDefaultTenant",
"IONOS_IT"]);else if(-1!==k.indexOf("mx.")||-1!==k.indexOf("mx-"))OAO.q.c.push(["setDefaultMarket","MX"]),OAO.q.c.push(["setDefaultLanguage","es_MX"]),OAO.q.c.push(["setDefaultTenant","IONOS_MX"]);else if(-1!==k.indexOf("pl.")||-1!==k.indexOf("pl-"))OAO.q.c.push(["setDefaultMarket","PL"]),OAO.q.c.push(["setDefaultLanguage","pl_PL"]),OAO.q.c.push(["setDefaultTenant","IONOS_PL"]);else if(-1!==k.indexOf("uk.")||-1!==k.indexOf("gb.")||-1!==k.indexOf("uk-")||-1!==k.indexOf("gb-"))OAO.q.c.push(["setDefaultMarket",
"UK"]),OAO.q.c.push(["setDefaultLanguage","en_GB"]),OAO.q.c.push(["setDefaultTenant","IONOS_UK"]);else if(-1!==k.indexOf("us.")||-1!==k.indexOf("com.")||-1!==k.indexOf("us-")||-1!==k.indexOf("com-"))OAO.q.c.push(["setDefaultMarket","US"]),OAO.q.c.push(["setDefaultLanguage","en_US"]),OAO.q.c.push(["setDefaultTenant","IONOS_US"])})();
(function(){if(window.OAO&&window.OAO.mobile){var k=document.querySelectorAll(".pagemessage[level\x3dinfo], .pagemessage[level\x3dsuccess], .custom-success-message .main-message, .pagemessages-container .subheadline-section, .sheet__section.sheet__section--activating .headline, .sheet__section.sheet__section--success .headline, .sheet__section.sheet__section--warning .headline"),m=document.querySelector(".abort-transaction")||!1;!1!==m&&m.addEventListener?m.addEventListener("click",function(){window.OAO.mobile.abortedAction()}):
!1!==m&&m.attachEvent&&m.attachEvent("onclick",function(){window.OAO.mobile.abortedAction()});k&&0<k.length&&(k=k[0],window.OAO.mobile.finishedAction(k.textContent||k.innerText))}})();OAO.q.ias=OAO.q.ias||[];(function(){var k=new URLSearchParams(window.location.search),m=k.get("mc")||null;m&&OAO.q.ias.push(["addVisitorData","mc",m]);(k=k.get("itc")||null)&&OAO.q.ias.push(["addVisitorData","itc",k])})();OAO.q.navigation=OAO.q.navigation||[];OAO.q.navigation.push(["setAppSwitchDisabled",!0]);
OAO.q.pageintegration=OAO.q.pageintegration||[];OAO.q.pageintegration.push(["disableDeeplinkingOnInit"]);OAO.q.c.push(["setApplication","WEBMAIL_LOGIN"]);OAO.q.c.push(["loadModule","globalnavigation"]);OAO.q.c.push(["loadModule","surveys"]);OAO.q.c.push(["loadModule","inpagelayer"]);OAO.q.c.push(["loadModule","statuspage"]);OAO.q.c.push(["loadModule","adserver"]);OAO.q.c.push(["loadModule","privacy-consent"]);
(function(){function k(e){var g=w[e];if(void 0!==g)return g.exports;g=w[e]={exports:{}};return m[e](g,g.exports,k),g.exports}var m={610:function(e,g,c){var f=c(756),d=c(887),b=c(664),h=c(242);e.exports={init:function(){},setApplication:function(a){f.setApplication(a)},setPageName:function(a){f.setPageName(a)},setFrontendToken:function(a){d.setFrontendToken(a)},setContractHash:function(a){d.setContractHash(a)},setMode:function(a){b.setMode(a)},setHost:function(a){b.setHost(a)},setMarket:function(a){b.setMarket(a)},
setDefaultMarket:function(a){b.setDefaultMarket(a)},setLanguage:function(a){b.setLanguage(a)},setDefaultLanguage:function(a){!1===b.getLanguage()&&b.setLanguage(a)},setTenant:function(a){b.setTenant(a)},setDefaultTenant:function(a){b.setDefaultTenant(a)},loadModule:function(a){try{c(767)("./"+a)}catch(p){h.reportError(p)}},data:{get visitor(){var a={};return d.getFrontendToken()&&(a.frontendToken=d.getFrontendToken()),d.getContractHash()&&(a.contractHash=d.getContractHash()),a},get tracking(){var a=
{};return f.getApplication()&&(a.application=f.getApplication()),f.getPageName()&&(a.page=f.getPageName()),a},get settings(){var a={};return a.isProd=b.isProd(),a.market=b.getMarket(),a.language=b.getLanguage(),a.host=b.getHost(),a.tenant=b.getTenant(),a}},__version:b.getVersion()}},39:function(e,g,c){function f(){var a=c(885);h.getFrontendToken()&&a.OAO.q.ias.push(["setFrontendSessionToken",h.getFrontendToken()]);h.getContractHash()&&a.OAO.q.ias.push(["setHashContractId",h.getContractHash()])}function d(){n.OAO.q.ias.push(["setMarket",
a.getMarket()]);n.OAO.q.ias.push(["setLanguage",a.getLanguage()]);n.OAO.q.ias.push(["setTenant",a.getTenant()])}function b(){n.OAO.q.ias.push(["setApplication",p.getApplication()]);n.OAO.q.ias.push(["setPage",p.getPageName()])}var h=c(887),a=c(664),p=c(756),l=c(85);e=c(616);var n=c(885);n.OAO=n.OAO||{};n.OAO.q=n.OAO.q||{};n.OAO.q.ias=n.OAO.q.ias||[];n.OAO.q.ias.push(["setHost",!1]);h.addChangeListener(f);a.addChangeListener(d);p.addChangeListener(b);f();d();b();e.onQueueFinished(function(){l.loadModule("ias/js/ias",
"5.31.1")})},11:function(e,g,c){function f(){l.OAO.q.navigation.push(["setFrontendToken",h.getFrontendToken()])}function d(){l.OAO.q.navigation.push(["setMarket",a.getMarket()]);l.OAO.q.navigation.push(["setLanguage",a.getLanguage()]);l.OAO.q.navigation.push(["setTenant",a.getTenant()]);l.OAO.q.navigation.push(["setBasePath",a.getHost()+"/navi-prelive/"])}function b(){l.OAO.q.navigation.push(["setClient",p.getApplication()]);l.OAO.q.navigation.push(["setPageName",p.getPageName()])}var h=
c(887),a=c(664),p=c(756);e=c(85);var l=c(885);l.OAO=l.OAO||{};l.OAO.q=l.OAO.q||{};l.OAO.q.navigation=l.OAO.q.navigation||[];f();d();b();h.addChangeListener(f);a.addChangeListener(d);p.addChangeListener(b);e.loadModule("navi-prelive/js/navigation","5.7.2")},609:function(e,g,c){function f(){l.OAO.q.navigation.push(["setFrontendToken",h.getFrontendToken()])}function d(){l.OAO.q.navigation.push(["setMarket",a.getMarket()]);l.OAO.q.navigation.push(["setLanguage",a.getLanguage()]);
l.OAO.q.navigation.push(["setTenant",a.getTenant()]);l.OAO.q.navigation.push(["setBasePath",a.getHost()+"/navi/"])}function b(){l.OAO.q.navigation.push(["setClient",p.getApplication()]);l.OAO.q.navigation.push(["setPageName",p.getPageName()])}var h=c(887),a=c(664),p=c(756);e=c(85);var l=c(885);l.OAO=l.OAO||{};l.OAO.q=l.OAO.q||{};l.OAO.q.navigation=l.OAO.q.navigation||[];f();d();b();h.addChangeListener(f);a.addChangeListener(d);p.addChangeListener(b);e.loadModule("navi/js/navigation","5.7.2")},
177:function(e,g,c){function f(){a.OAO.q.pageintegration.push(["setMarket",b.getMarket()]);a.OAO.q.pageintegration.push(["setLanguage",b.getLanguage()]);a.OAO.q.pageintegration.push(["setBasePath",b.getHost()+"/inpagelayer-prelive/"])}function d(){a.OAO.q.pageintegration.push(["setClient",h.getApplication()]);a.OAO.q.pageintegration.push(["setPageName",h.getPageName()])}var b=c(664),h=c(756);e=c(85);var a=c(885);a.OAO=a.OAO||{};a.OAO.q=a.OAO.q||{};a.OAO.q.pageintegration=a.OAO.q.pageintegration||
[];f();d();b.addChangeListener(f);h.addChangeListener(d);e.loadModule("inpagelayer-prelive/js/inpagelayer","4.1.0")},362:function(e,g,c){function f(){a.OAO.q.pageintegration.push(["setMarket",b.getMarket()]);a.OAO.q.pageintegration.push(["setLanguage",b.getLanguage()]);a.OAO.q.pageintegration.push(["setBasePath",b.getHost()+"/inpagelayer/"])}function d(){a.OAO.q.pageintegration.push(["setClient",h.getApplication()]);a.OAO.q.pageintegration.push(["setPageName",h.getPageName()])}
var b=c(664),h=c(756);e=c(85);var a=c(885);a.OAO=a.OAO||{};a.OAO.q=a.OAO.q||{};a.OAO.q.pageintegration=a.OAO.q.pageintegration||[];f();d();b.addChangeListener(f);h.addChangeListener(d);e.loadModule("inpagelayer/js/inpagelayer","4.1.0")},319:function(e,g,c){function f(){a.OAO.q.passwordindicator.push(["setMarket",b.getMarket()]);a.OAO.q.passwordindicator.push(["setLanguage",b.getLanguage()]);a.OAO.q.passwordindicator.push(["setBasePath",b.getHost()+"/password-indicator/"])}function d(){a.OAO.q.passwordindicator.push(["setClient",
h.getApplication()]);a.OAO.q.passwordindicator.push(["setPageName",h.getPageName()])}var b=c(664),h=c(756);e=c(85);var a=c(885);a.OAO=a.OAO||{};a.OAO.q=a.OAO.q||{};a.OAO.q.passwordindicator=a.OAO.q.passwordindicator||[];f();d();b.addChangeListener(f);h.addChangeListener(d);e.loadModule("password-indicator/js/password-indicator","2.8.1")},8:function(e,g,c){function f(){b.OAO.q.privacyconsent.push(["setMarket",d.getMarket()]);b.OAO.q.privacyconsent.push(["setLanguage",d.getLanguage()])}
e=c(85);var d=c(664),b=c(885);b.OAO=b.OAO||{};b.OAO.q=b.OAO.q||{};b.OAO.q.privacyconsent=b.OAO.q.privacyconsent||[];f();d.addChangeListener(f);e.loadModule("privacyconsent-prelive/js/privacyconsent","3.0.3")},731:function(e,g,c){function f(){b.OAO.q.privacyconsent.push(["setMarket",d.getMarket()]);b.OAO.q.privacyconsent.push(["setLanguage",d.getLanguage()])}e=c(85);var d=c(664),b=c(885);b.OAO=b.OAO||{};b.OAO.q=b.OAO.q||{};b.OAO.q.privacyconsent=b.OAO.q.privacyconsent||
[];f();d.addChangeListener(f);e.loadModule("privacyconsent/js/privacyconsent","2.0.0")},229:function(e,g,c){function f(){l.OAO.q.notifications.push(["setFrontendToken",h.getFrontendToken()])}function d(){l.OAO.q.notifications.push(["setMarket",a.getMarket()]);l.OAO.q.notifications.push(["setLanguage",a.getLanguage()]);l.OAO.q.notifications.push(["setBasePath",a.getHost()+"/pushnotifications/"])}function b(){l.OAO.q.notifications.push(["setClient",p.getApplication()]);l.OAO.q.notifications.push(["setPageName",
p.getPageName()])}var h=c(887),a=c(664),p=c(756);e=c(85);var l=c(885);l.OAO=l.OAO||{};l.OAO.q=l.OAO.q||{};l.OAO.q.notifications=l.OAO.q.notifications||[];f();d();b();h.addChangeListener(f);a.addChangeListener(d);p.addChangeListener(b);e.loadModule("pushnotifications/js/pushnotifications","2.3.3")},119:function(e,g,c){function f(){a.OAO.q.statuspage.push(["setMarket",b.getMarket()]);a.OAO.q.statuspage.push(["setLanguage",b.getLanguage()]);a.OAO.q.statuspage.push(["setBasePath",b.getHost()+
"/statuspage/"])}function d(){a.OAO.q.statuspage.push(["setClient",h.getApplication()]);a.OAO.q.statuspage.push(["setPageName",h.getPageName()])}var b=c(664),h=c(756);e=c(85);var a=c(885);a.OAO=a.OAO||{};a.OAO.q=a.OAO.q||{};a.OAO.q.statuspage=a.OAO.q.statuspage||[];f();d();b.addChangeListener(f);h.addChangeListener(d);e.loadModule("statuspage/js/statuspage","2.1.2")},150:function(e,g,c){function f(){var a=c(885);h.getFrontendToken()&&a.OAO.q.surveys.push(["setFrontendSessionToken",
h.getFrontendToken()]);h.getContractHash()&&a.OAO.q.surveys.push(["setHashContractId",h.getContractHash()])}function d(){n.OAO.q.surveys.push(["setMarket",a.getMarket()]);n.OAO.q.surveys.push(["setLanguage",a.getLanguage()]);n.OAO.q.surveys.push(["setTenant",a.getTenant()])}function b(){n.OAO.q.surveys.push(["setClient",p.getApplication()]);n.OAO.q.surveys.push(["setPage",p.getPageName()])}var h=c(887),a=c(664),p=c(756),l=c(85);e=c(616);var n=c(885);n.OAO=n.OAO||{};n.OAO.q=n.OAO.q||{};n.OAO.q.surveys=
n.OAO.q.surveys||[];h.addChangeListener(f);a.addChangeListener(d);p.addChangeListener(b);f();d();b();e.onQueueFinished(function(){l.loadModule("surveys/js/surveys","1.5.0")})},488:function(e,g,c){function f(){a.OAO.q.tour.push(["setMarket",b.getMarket()]);a.OAO.q.tour.push(["setLanguage",b.getLanguage()]);a.OAO.q.tour.push(["setBasePath",b.getHost()+"/welcometour/"])}function d(){a.OAO.q.tour.push(["setClient",h.getApplication()]);a.OAO.q.tour.push(["setPageName",h.getPageName()])}var b=
c(664),h=c(756);e=c(85);var a=c(885);a.OAO=a.OAO||{};a.OAO.q=a.OAO.q||{};a.OAO.q.tour=a.OAO.q.tour||[];f();d();b.addChangeListener(f);h.addChangeListener(d);e.loadModule("welcometour/js/welcome-tour","3.0.0")},664:function(e,g,c){var f;g=c(584);var d=g.Mode,b=g.Market,h=g.Language,a=g.Tenant;g=c(418);c=c(187).EventEmitter;var p=d.PROD,l=!1,n=b.DE,k=!1,m=a.IONOS_DE,q=!1;c=g({},c.prototype,{emitChange:function(){this.emit("change")},addChangeListener:function(a){this.on("change",a)},
getVersion:function(){return"1.0.0"},isProd:function(){return p===d.PROD},setMode:function(a){a?(a=a.toUpperCase(),d[a]||(a=d.PROD)):a=d.PROD;var b=p!==a;p=a;b&&this.emitChange()},getMarket:function(){return l||n},setMarket:function(a){a?("GB"===(a=a.toUpperCase())&&(a=b.UK),b[a]||(a=b.DE)):a=b.DE;var d=l!==a;l=a;d&&this.emitChange()},setDefaultMarket:function(a){a?("GB"===(a=a.toUpperCase())&&(a=b.UK),b[a]||(a=b.DE)):a=b.DE;var d=n!==a;n=a;d&&this.emitChange()},getLanguage:function(){return k},setLanguage:function(a){if(a&&
-1!==a.indexOf("_")){var b,d,c=a.indexOf("_");(b=a.substr(0,c)||"",d=a.substr(c+1)||"",b=b.toLowerCase(),d=d.toUpperCase(),h[a=b+"_"+d])?(b=k!==a,k=a,b&&this.emitChange()):k=!1}else k=!1},getTenant:function(){return q||m},setTenant:function(b){b?(b=b.toUpperCase(),a[b]||(b=a.IONOS_DE)):b=a.IONOS_DE;var d=q!==b;q=b;d&&this.emitChange()},setDefaultTenant:function(b){b?(b=b.toUpperCase(),a[b]||(b=a.IONOS_DE)):b=a.IONOS_DE;var d=m!==b;m=b;d&&this.emitChange()},getHost:function(){return f},setHost:function(a){var b=
f!==a;f=a||!1;b&&this.emitChange()}});e.exports=c},756:function(e,g,c){g=c(418);c=c(187).EventEmitter;var f=!1,d=!1;c=g({},c.prototype,{emitChange:function(){this.emit("change")},addChangeListener:function(b){this.on("change",b)},getApplication:function(){return f},setApplication:function(b){var d=f!==b;f=b||!1;d&&this.emitChange()},getPageName:function(){return d},setPageName:function(b){if(b){try{b=(b=(b=(b=b.replaceAll(/^\s+|\s+$/g,"")).replaceAll(/\s\s+/g," ")).replaceAll(" ","-")).replaceAll(/#(.*)/g,
"")}catch(a){b=(b=(b=(b=b.replace(/^\s+|\s+$/g,"")).replace(/\s\s+/g," ")).replace(" ","-")).replace(/#(.*)/g,"")}b=b.replace(/;jsessionid=([A-Za-z0-9.]+)/,"")}var c=d!==b;d=b||!1;c&&this.emitChange()}});e.exports=c},887:function(e,g,c){g=c(418);c=c(187).EventEmitter;var f=!1,d=!1;c=g({},c.prototype,{emitChange:function(){this.emit("change")},addChangeListener:function(b){this.on("change",b)},getFrontendToken:function(){return f},setFrontendToken:function(b){var d=f!==b;f=b||!1;d&&this.emitChange()},
getContractHash:function(){return d},setContractHash:function(b){var c=d!==b;d=b||!1;c&&this.emitChange()}});e.exports=c},355:function(e,g,c){var f=c(929);g=c(664);c=c(756);(f=f.getDefaultHostnameByScriptTag())&&g.setHost(f);(g=function(){var d=window.location;if(!d||!d.pathname)return!1;for(var d=d.pathname.split("/"),b=0;b<d.length;b+=1)if(d[b]&&""!==d[b]){var c=d[b].split("#",2)[0].split("\\?",2)[0].split(";",2)[0];if(c&&""!==c)return c}return"HOME"}())&&c.setPageName(g);e.exports={}},616:function(e,
g,c){g=c(187).EventEmitter;var f=c(418);c=c(885);c.OAO=c.OAO||{};c.OAO.q=c.OAO.q||{};var d=c.OAO.q.c||[],b=!1,h=f({},g.prototype,{addPushListener:function(a){this.on("push",a)},removePushListener:function(a){this.removeListener("push",a)},onQueueFinished:function(a){b?window.setTimeout(a,0):this.on("ready",a)},push:function(){if(!(1>arguments.length)){var a=0>=arguments.length?void 0:arguments[0];if(a&&a.length&&!(1>a.length)){var b=a[0],a=a.slice(1);this.emit("push",b,a)}}},process:function(){for(var a=
0;a<d.length;a+=1){var c=[];c.push(d[a]);h.push.apply(h,c)}d=[];b=!0;this.emit("ready")}});c.OAO.q.c={push:function(){for(var a=arguments.length,b=Array(a),d=0;d<a;d++)b[d]=arguments[d];h.push.apply(h,b)}};e.exports=h},85:function(e,g,c){var f=c(664),d=c(929),b=c(318);e.exports={loadScript:d.loadScript,loadModule:function(c,a,g){c={host:f.getHost(),path:c+".js",query:{v:a||1}};f.isProd()&&(c.protocol="https");d.loadScript(b.build(c),g)}}},925:function(e,g,c){var f=c(616),d=c(610),b=c(242);b.setClient("TAG_MANAGER");
b.setClientVersion("1.0.0");b.setSentryDsn("https://236c7da13ef44014830813657f2e5fb7@sentry.ionos.com/25");b.setSentryProject("tagmanager-fi");b.init();g=function(){f.addPushListener(function(b,a){b&&(a=a||[],"function"==typeof d[b]&&d[b].apply(d,a))});try{c(355),f.process(),d.init()}catch(h){b.reportError(h)}return d}();e.exports=g},584:function(e){e.exports={Mode:{PROD:"PROD",STAGE:"STAGE",LOCAL:"LOCAL",DEMO:"DEMO"},Market:{CA:"CA",DE:"DE",ES:"ES",FR:"FR",IT:"IT",MX:"MX",PL:"PL",UK:"UK",GB:"UK",
US:"US",NL:"NL"},Language:{en_CA:"en_CA",de_DE:"de_DE",es_ES:"es_ES",fr_FR:"fr_FR",it_IT:"it_IT",es_MX:"es_MX",pl_PL:"pl_PL",en_GB:"en_GB",en_US:"en_US",nl_NL:"nl_NL",sv_SE:"sv_SE"},Tenant:{IONOS:"IONOS_DE",IONOS_DE:"IONOS_DE",IONOS_ES:"IONOS_ES",IONOS_FR:"IONOS_FR",IONOS_IT:"IONOS_IT",IONOS_MX:"IONOS_MX",IONOS_US:"IONOS_US",IONOS_UK:"IONOS_UK",IONOS_GB:"IONOS_UK",IONOS_CA:"IONOS_CA",IONOS_PL:"IONOS_PL",IONOS_CLOUD_DE:"IONOS_CLOUD_DE",IONOS_CLOUD_ES:"IONOS_CLOUD_ES",IONOS_CLOUD_FR:"IONOS_CLOUD_FR",
IONOS_CLOUD_IT:"IONOS_CLOUD_IT",IONOS_CLOUD_MX:"IONOS_CLOUD_MX",IONOS_CLOUD_US:"IONOS_CLOUD_US",IONOS_CLOUD_UK:"IONOS_CLOUD_UK",IONOS_CLOUD_GB:"IONOS_CLOUD_UK",IONOS_CLOUD_CA:"IONOS_CLOUD_CA",STRATO_DE:"STRATO_DE",STRATO_NL:"STRATO_NL",STRATO_ES:"STRATO_ES",STRATO_EA:"STRATO_EA",STRATO_FR:"STRATO_FR",STRATO_IT:"STRATO_IT",STRATO_GB:"STRATO_GB",STRATO_SE:"STRATO_SE",SEDO_DE:"SEDO_DE",SEDO_ES:"SEDO_ES",SEDO_UK:"SEDO_UK",SEDO_FR:"SEDO_FR",SEDO_US:"SEDO_US",ARSYS:"ARSYS",ARSYS_FR:"ARSYS_FR",ARSYS_ES_EN:"ARSYS_ES_EN",
FASTHOSTS:"FASTHOSTS",HOME_PL:"HOME_PL",HOME_PL_LEGACY:"HOME_PL_LEGACY",PIENSA_SOLUTIONS:"PIENSA_SOLUTIONS",UNITED_DOMAINS:"UNITED_DOMAINS",WORLD4YOU_DE:"WORLD4YOU_DE",WORLD4YOU_US:"WORLD4YOU_US",INTERNETX_DE:"INTERNETX_DE",INTERNETX_US:"INTERNETX_US"},DefaultLanguageForMarket:{CA:"en_CA",DE:"de_DE",ES:"es_ES",FR:"fr_FR",IT:"it_IT",MX:"es_MX",PL:"pl_PL",UK:"en_GB",US:"en_US",NL:"nl_NL"}}},242:function(e,g,c){function f(){return a&&a.performance&&"function"==typeof a.performance.now?a.performance.now():
(new Date).getTime()}var d,b,h=c(929),a=c(885),p=(a.document,"UNKNOWN"),l=p,k=p,m=!1,v=!1,q=!1,t=!1,u=!1,y=!1,z=f();e.exports={setClient:function(a){l=a||p},setClientVersion:function(a){k=a||p},setSentryDsn:function(a){m=a||!1},setSentryProject:function(a){v=a||!1},setSentryEnvironment:function(a){q=a||!1;y&&this.init()},init:function(){if(!1!==m)if(a.Sentry&&a.Sentry.BrowserClient&&window.Sentry.Hub){var c={dsn:m,environment:q||"prod",beforeSend:function(a){return a.extra&&a.extra.oaoClient&&a.extra.oaoClient===
l?a:null}};!1!==v&&(c.release=v+"@"+k);c=new a.Sentry.BrowserClient(c);(t=new a.Sentry.Hub).bindClient(c);y=!0;!1!==u&&(this.reportError(u,d,b),u=!1,d=!1,b=!1)}else c=h.getDefaultHostnameByScriptTag()||"frontend-services.ionos.com/t",h.loadScript("https://"+c+"/sentry/bundle.min.js",function(){this.init()}.bind(this))},reportError:function(a,c,h){if(!1===t)return this.init(),u=a,d=c,void(b=h);t.withScope(function(b){b.setExtra("oaoClient",l);b.setExtra("oaoClientVersion",k);b.setExtra("oaoTimeSinceInit",
function(a){if(!a)return!1;var b=f();return!!b&&Math.ceil(b-a)}(z));b.setExtra("oaoUrl",window.location.href||"");c&&b.setExtras(c);h&&b.setTags(h);t.captureException(a)})},getCurrentTime:f}},929:function(e,g,c){var f=c(242),d=c(885).document;e.exports={loadScript:function(b,c){var a,h,g,e=!1;return(h=d.createElement("script")).type="text/javascript",h.async=!0,"function"==typeof c&&(g=function(){if(!(e||this.readyState&&"loaded"!==this.readyState&&"complete"!==this.readyState)){e=!0;try{c()}catch(r){f.reportError(r)}h.onload=
null;h.onreadystatechange=null}},h.onload=g,h.onreadystatechange=g),h.src=b,(a=d.getElementsByTagName("script")[0]).parentNode.insertBefore(h,a),h},getDefaultHostnameByScriptTag:function(){var b;b=document;var c=[];b=b.querySelectorAll&&0<(c=b.querySelectorAll("#oaotag")).length?c[0]:null;if(!b)return!1;c=b.src;if(!c)return!1;c=c.replace("https://","");"//"===(c=c.replace("http://","")).substr(0,2)&&(c=c.substr(2));b=c.indexOf("/tag");return-1!==b&&c.substr(0,b)}}},318:function(e,g,c){var f=c(885).document;
e.exports={build:function(c,b){var d,a,g=encodeURIComponent,f="",e="";if(!(c&&(f+=c.protocol?c.protocol+":":"",a=c.host)))return!1;if("/"===a.substr(-1)&&(a=a.substr(0,a.length-1)),f+=!0===b?a+"/":"//"+a+"/",c.path&&("/"===c.path.substr(0,1)&&(c.path=c.path.substr(1)),f+=c.path),c.query){for(d in c.query)c.query.hasOwnProperty(d)&&(e+=""===e?"?":"\x26",e+=d+"\x3d"+g(c.query[d]));f+=e}return f},getQueryParams:function(c){var b,d,a,g,e={};if(!c&&(b=f.location,!b||!(c=b.search)))return e;if("?"===c.substr(0,
1)&&(c=c.substr(1)),b=c.split("\x26"))for(c=0;c<b.length;c+=1)b[c]&&2===(d=b[c].split("\x3d")).length&&(a=d[0],g=d[1],a&&g&&(e[a]=g));return e},ensureSameProtocol:function(c){var b=f.location.protocol;return!!c&&(0===c.indexOf(b)||("http:"===b?c=c.replace("https://","http://"):"https:"===b&&(c=c.replace("http://","https://"))),c)},isFullQualified:function(c){return!!c&&(0===c.indexOf("http://")||0===c.indexOf("https://"))}}},187:function(e){function g(){g.init.call(this)}function c(a){if("function"!=
typeof a)throw new TypeError('The "listener" argument must be of type Function. Received type '+typeof a);}function f(a,b,d,h){var u,f,e;if(c(d),void 0===(f=a._events)?(f=a._events=Object.create(null),a._eventsCount=0):(void 0!==f.newListener&&(a.emit("newListener",b,d.listener?d.listener:d),f=a._events),e=f[b]),void 0===e)f[b]=d,++a._eventsCount;else if("function"==typeof e?e=f[b]=h?[d,e]:[e,d]:h?e.unshift(d):e.push(d),0<(u=void 0===a._maxListeners?g.defaultMaxListeners:a._maxListeners)&&e.length>
u&&!e.warned)e.warned=!0,d=Error("Possible EventEmitter memory leak detected. "+e.length+" "+String(b)+" listeners added. Use emitter.setMaxListeners() to increase limit"),d.name="MaxListenersExceededWarning",d.emitter=a,d.type=b,d.count=e.length,console&&console.warn&&console.warn(d);return a}function d(){if(!this.fired)return this.target.removeListener(this.type,this.wrapFn),this.fired=!0,0===arguments.length?this.listener.call(this.target):this.listener.apply(this.target,arguments)}function b(a,
b,c){a={fired:!1,wrapFn:void 0,target:a,type:b,listener:c};b=d.bind(a);return b.listener=c,a.wrapFn=b,b}function h(a,b,c){a=a._events;if(void 0===a)return[];b=a[b];if(void 0===b)c=[];else if("function"==typeof b)c=c?[b.listener||b]:[b];else if(c)for(c=Array(b.length),a=0;a<c.length;++a)c[a]=b[a].listener||b[a];else c=k(b,b.length);return c}function a(a){var b=this._events;if(void 0!==b){a=b[a];if("function"==typeof a)return 1;if(void 0!==a)return a.length}return 0}function k(a,b){for(var c=Array(b),
d=0;d<b;++d)c[d]=a[d];return c}function l(a,b,c,d){if("function"==typeof a.on)d.once?a.once(b,c):a.on(b,c);else{if("function"!=typeof a.addEventListener)throw new TypeError('The "emitter" argument must be of type EventEmitter. Received type '+typeof a);a.addEventListener(b,function A(e){d.once&&a.removeEventListener(b,A);c(e)})}}var n,m="object"==typeof Reflect?Reflect:null,v=m&&"function"==typeof m.apply?m.apply:function(a,b,c){return Function.prototype.apply.call(a,b,c)};n=m&&"function"==typeof m.ownKeys?
m.ownKeys:Object.getOwnPropertySymbols?function(a){return Object.getOwnPropertyNames(a).concat(Object.getOwnPropertySymbols(a))}:function(a){return Object.getOwnPropertyNames(a)};var q=Number.isNaN||function(a){return a!=a};e.exports=g;e.exports.once=function(a,b){return new Promise(function(c,d){function e(c){a.removeListener(b,f);d(c)}function f(){"function"==typeof a.removeListener&&a.removeListener("error",e);c([].slice.call(arguments))}l(a,b,f,{once:!0});"error"!==b&&function(a,b,c){"function"==
typeof a.on&&l(a,"error",b,c)}(a,e,{once:!0})})};g.EventEmitter=g;g.prototype._events=void 0;g.prototype._eventsCount=0;g.prototype._maxListeners=void 0;var t=10;Object.defineProperty(g,"defaultMaxListeners",{enumerable:!0,get:function(){return t},set:function(a){if("number"!=typeof a||0>a||q(a))throw new RangeError('The value of "defaultMaxListeners" is out of range. It must be a non-negative number. Received '+a+".");t=a}});g.init=function(){void 0!==this._events&&this._events!==Object.getPrototypeOf(this)._events||
(this._events=Object.create(null),this._eventsCount=0);this._maxListeners=this._maxListeners||void 0};g.prototype.setMaxListeners=function(a){if("number"!=typeof a||0>a||q(a))throw new RangeError('The value of "n" is out of range. It must be a non-negative number. Received '+a+".");return this._maxListeners=a,this};g.prototype.getMaxListeners=function(){return void 0===this._maxListeners?g.defaultMaxListeners:this._maxListeners};g.prototype.emit=function(a){for(var b=[],c=1;c<arguments.length;c++)b.push(arguments[c]);
var c="error"===a,d=this._events;if(void 0!==d)c=c&&void 0===d.error;else if(!c)return!1;if(c){var e;if(0<b.length&&(e=b[0]),e instanceof Error)throw e;b=Error("Unhandled error."+(e?" ("+e.message+")":""));throw b.context=e,b;}c=d[a];if(void 0===c)return!1;if("function"==typeof c)v(c,this,b);else for(e=c.length,d=k(c,e),c=0;c<e;++c)v(d[c],this,b);return!0};g.prototype.addListener=function(a,b){return f(this,a,b,!1)};g.prototype.on=g.prototype.addListener;g.prototype.prependListener=function(a,b){return f(this,
a,b,!0)};g.prototype.once=function(a,d){return c(d),this.on(a,b(this,a,d)),this};g.prototype.prependOnceListener=function(a,d){return c(d),this.prependListener(a,b(this,a,d)),this};g.prototype.removeListener=function(a,b){var d,e,f,g,h;if((c(b),void 0===(e=this._events))||void 0===(d=e[a]))return this;if(d===b||d.listener===b)0==--this._eventsCount?this._events=Object.create(null):(delete e[a],e.removeListener&&this.emit("removeListener",a,d.listener||b));else if("function"!=typeof d){f=-1;for(g=
d.length-1;0<=g;g--)if(d[g]===b||d[g].listener===b){h=d[g].listener;f=g;break}if(0>f)return this;if(0===f)d.shift();else{for(;f+1<d.length;f++)d[f]=d[f+1];d.pop()}1===d.length&&(e[a]=d[0]);void 0!==e.removeListener&&this.emit("removeListener",a,h||b)}return this};g.prototype.off=g.prototype.removeListener;g.prototype.removeAllListeners=function(a){var b,c;if(void 0===(c=this._events))return this;if(void 0===c.removeListener)return 0===arguments.length?(this._events=Object.create(null),this._eventsCount=
0):void 0!==c[a]&&(0==--this._eventsCount?this._events=Object.create(null):delete c[a]),this;if(0===arguments.length){var d=Object.keys(c);for(c=0;c<d.length;++c)"removeListener"!==(b=d[c])&&this.removeAllListeners(b);return this.removeAllListeners("removeListener"),this._events=Object.create(null),this._eventsCount=0,this}if("function"==typeof(b=c[a]))this.removeListener(a,b);else if(void 0!==b)for(c=b.length-1;0<=c;c--)this.removeListener(a,b[c]);return this};g.prototype.listeners=function(a){return h(this,
a,!0)};g.prototype.rawListeners=function(a){return h(this,a,!1)};g.listenerCount=function(b,c){return"function"==typeof b.listenerCount?b.listenerCount(c):a.call(b,c)};g.prototype.listenerCount=a;g.prototype.eventNames=function(){return 0<this._eventsCount?n(this._events):[]}},418:function(e){var g=Object.getOwnPropertySymbols,c=Object.prototype.hasOwnProperty,f=Object.prototype.propertyIsEnumerable;e.exports=function(){try{if(!Object.assign)return!1;var c=new String("abc");if(c[5]="de","5"===Object.getOwnPropertyNames(c)[0])return!1;
for(var b={},c=0;10>c;c++)b["_"+String.fromCharCode(c)]=c;if("0123456789"!==Object.getOwnPropertyNames(b).map(function(a){return b[a]}).join(""))return!1;var e={};return"abcdefghijklmnopqrst".split("").forEach(function(a){e[a]=a}),"abcdefghijklmnopqrst"===Object.keys(Object.assign({},e)).join("")}catch(a){return!1}}()?Object.assign:function(d,b){var e,a,k;if(null==d)throw new TypeError("Object.assign cannot be called with null or undefined");k=Object(d);for(var l=1;l<arguments.length;l++){for(var m in e=
Object(arguments[l]))c.call(e,m)&&(k[m]=e[m]);if(g){a=g(e);for(var r=0;r<a.length;r++)f.call(e,a[r])&&(k[a[r]]=e[a[r]])}}return k}},767:function(e,g,c){function f(b){b=d(b);return c(b)}function d(d){if(!c.o(b,d))throw d=Error("Cannot find module '"+d+"'"),d.code="MODULE_NOT_FOUND",d;return b[d]}var b={"./adserver":39,"./adserver.js":39,"./globalnavigation":609,"./globalnavigation-prelive":11,"./globalnavigation-prelive.js":11,"./globalnavigation.js":609,"./inpagelayer":362,"./inpagelayer-prelive":177,
"./inpagelayer-prelive.js":177,"./inpagelayer.js":362,"./password-indicator":319,"./password-indicator.js":319,"./privacy-consent":731,"./privacy-consent-prelive":8,"./privacy-consent-prelive.js":8,"./privacy-consent.js":731,"./pushnotifications":229,"./pushnotifications.js":229,"./statuspage":119,"./statuspage.js":119,"./surveys":150,"./surveys.js":150,"./welcometour":488,"./welcometour.js":488};f.keys=function(){return Object.keys(b)};f.resolve=d;e.exports=f;f.id=767},885:function(e){e.exports=
window}},w={};k.o=function(e,g){return Object.prototype.hasOwnProperty.call(e,g)};var x=k(925);(OAO=void 0===OAO?{}:OAO).c=x})();